config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :orders, except: :destroy

  namespace :api do
    resources :order_transits, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'orders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  enum delivery_status: %i[pending_pickup in_transit delivered]

  validates :pickup_address, presence: true
  validates :delivery_address, presence: true
  validates :item_name, presence: true

  validate :check_delivery_status, if: :delivery_address_changed?

  belongs_to :user
  has_many :order_transits, dependent: :destroy

  def check_delivery_status
    errors.add(:delivery_address, "Can't update after delivery") if delivered?
  end
end

app/models/order_transit.rb
class OrderTransit < ApplicationRecord
  attr_accessor :status

  validates :location, presence: true
  validates :agent_name, presence: true
  validates :agent_phone_number, presence: true

  belongs_to :order
  after_save :update_order_status
  after_create_commit :brodcast_order_update

  private

  # updating status of parent order

  def update_order_status
    order.delivery_status = status
    order.save
  end

  def brodcast_order_update
    OrderUpdateService.inform_client('orders', self)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name,  presence: true
  validates :password, presence: true, confirmation: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  has_many :orders, dependent: :destroy
end

app/models/user/sign_in.rb
class User::SignIn < ActiveType::Object
  # plain model for handle sign in
  # not holding any tables
  attribute :email
  attribute :password

  validates :email, presence: true
  validates :password, presence: true

  validate :existance_user
  validate :authenticate_user

  private

  def existance_user
    errors.add(:email, 'User is not found ') if user.nil?
  end

  def authenticate_user
    errors.add(:password, 'Invalid Credentials') unless user && user.authenticate(password)
  end

  # create user object from email
  def user
    @user ||= User.find_by(email: email)
  end
end

app/controllers/api/order_transits_controller.rb
class Api::OrderTransitsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  # haveto impliemnetapi tokenbased authentication

  def create
    order_transit = OrderTransit.new(order_transit_params)
    if order_transit.save
      render json: order_transit, status: :created
    else
      render json: order_transit, status: 500, message: "Can't able to add"
    end
  end

  private
  
  def order_transit_params
    params.require(:order_transit).permit(:location, :status, :order_id, :agent_name, :agent_phone_number)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  protected

  def authenticate_user
    redirect_to login_path unless current_user.present?
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user
  before_action :set_order, only: %i[show edit update destroy]
  # check authorization to manage  order
  before_action :check_authorized_user, only: %i[show edit update destroy]
  helper_method :previous_address

  def index
    @orders = current_user.orders
  end

  def create
    build_order
    if @order.save
      flash[:success] = 'Successfully Orderd'
      redirect_to order_path(@order)
    else
      flash[:danger] = 'Have Some problem to create order'
      render 'new'
    end
  end

  def new
    @order = Order.new
  end

  def show; end

  def edit; end

  def update
    if @order.update(order_params)
      flash[:success] = 'Succesafully upddated order details'
      redirect_to order_path(@order)
    else
      flash[:danger] = 'Error, Please check your inputs'
      render 'new'
    end
  end

  private

  def check_authorized_user
    render text: 'Forbidden', status: 403 unless @order.user_id == current_user.id
  end

  # fetch previous delivery address
  def previous_address
    @previous_delivery_address = current_user.orders.select('distinct delivery_address')
  end

  def set_order
    @order ||= Order.includes(:order_transits).find(params[:id])
  end

  def build_order
    @order = Order.new(order_params.merge(user_id: current_user.id))
  end

  def order_params
    params.require(:order).permit(:pickup_address, :delivery_address, :item_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # controller for handling user session
  # before_action :authenticate_user, only: [:destroy]

  def new
    @session = User::SignIn.new
  end

  def create
    build_session
    if @session.save
      set_user_session
      flash[:success] = 'You successfully login to your account'
      redirect_to orders_path
    else
      flash[:danger] = 'Invalid login'
      render 'new', status: 403
    end
  end

  def destroy
    session[:user_id], @current_user = nil
    redirect_to login_path
  end

  private

  def build_session
    @session = User::SignIn.new(sign_in_params)
  end

  def set_user_session
    session[:user_id] = user.id
  end

  def user
    User.find_by(email: sign_in_params[:email])
  end

  def sign_in_params
    params.require(:user_sign_in).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    build_user
    if @user.save
      flash[:success] = 'Signup was Successful'
      redirect_to login_path
    else
      flash[:danger] = 'Sign up was Unsuccessful'
      render 'new', status: 400
    end
  end

  private

  def build_user
    @user = User.new(user_params)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Helper to checkuser sign in
  def signd_in?
    current_user.present?
  end
end

app/helpers/form_helper.rb
module FormHelper
  # custom error message
  def error_message(form, field)
    if form.object.errors[field].present?
      error_messsage =  form.object.errors[field].try(:first).to_s
      content_tag(:div, error_messsage, class: 'help-inline')
    end
 end
end

app/helpers/order_transits_helper.rb
module OrderTransitsHelper
  def order_delivered?
    @order.delivered?
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-dark bg-inverse" style="padding: 20px">
  <%= link_to "Delivery App", root_path,:class=>"navbar-brand" %>
  <ul class="nav navbar-nav navbar-right">
    <li class="nav-item">
        <% if signd_in? %>
        <%= link_to "Home",root_path,class: "navbar-brand" %>
        <%= link_to "Sign Out",logout_path, method: :delete,class: "navbar-brand" %>
        <%else%>
           <%= link_to "Log in",login_path,class: "navbar-brand" %>
           <%= link_to "Sign Up",signup_path,class: "navbar-brand" %>
        <%end%>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= action_cable_meta_tag %>
  </head>
  <body class='container' style="margin-top: 150px">
    <%=render 'layouts/header'%>
    <% flash.each do |key, value| %>
       <div class="alert alert-<%=key%>"><%= value %></div>
     <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<table style='width: 100%'>
  <tr>
    <td>
      <div class="col-md-8 col-md-offset-1">
        <%= form_for @order do |form| %>
          <div class="form-group">
            <%= form.label :item_name%>
            <%= form.text_field :item_name,:class=>'form-control input-md' %>
            <%= error_message form, :item_name%>
          </div>
          <div class="form-group">
            <%= form.label :pickup_address %>
            <%= form.text_area :pickup_address,:class=>'form-control input-md' %>
            <%= error_message form,:pickup_address%>
            </div>
          <% unless order_delivered? %>
              <div class="form-group">
                <%= form.label :delivery_address %>
                <%= form.text_area :delivery_address,:class=>'form-control input-md',id: 'delivery-text-area' %>
                <%= error_message form,:pickup_address%>
              </div>
          <% end %>
          <%= form.submit "Submit",:class=>'btn btn-primary'%>
         <%end%>
      </div>
    </td>
<table>
    <td>
      <div class="col-md-5 col-md-offset-3">
        <ul class="list-group">
      <% unless previous_address.empty? %>
       <h3>Select from previous Address</h3>
      <%end%>
        <% previous_address.each do |address|%>
          <% unless address.delivery_address.empty? %>
            <li class="list-group-item" onclick="copyAddressToDelivery(this)">
              <%=address.delivery_address%>
            </li>
            <%else%>

           <%end%>
         <%end%>
       </ul>
     </div>
    </td>
  </tr>
</table>

app/views/orders/edit.html.erb
<h1>Order Edit</h1>
<%=render  "orders/form" %>

app/views/orders/index.html.erb
<h1>Your orders</h1>

<%= link_to "Create Order", new_order_path, class: 'btn btn-primary right'%>
<ul class="list-group">
  <%@orders.each do |order| %>
     <li class="list-group-item" style="height: 50px">
       <span class="badge"> <%= order.delivery_status.humanize %></span>
       <%=link_to order.item_name, order_path(order) %>
     </li>
  <% end%>
</ul>

app/views/orders/new.html.erb
<%=render "orders/form"%>

app/views/orders/show.html.erb
<% unless order_delivered? %>
  <%= link_to 'Edit Order',edit_order_path(@order),class: 'btn btn-primary link-item'%>
<%end%>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"> Item - <%=@order.item_name%></h3>
    </div>
    <div class="panel-body">
      <h4> Pickup Adress : <%=@order.pickup_address%> </h4>
      <h4> Delivery Address : <%=@order.delivery_address%></h4>
      <h4> Order date : <%=@order.created_at.strftime("%a , %I:%M - %F")%> </h4>
      <h4> Order status : <%=@order.delivery_status.humanize%> </h4>

    </div>
  </div>

  <table id="order_path-<%=@order.id%>" class="table table-striped">
    <% if @order.order_transits.present?%>
      <thead>
        <tr>
          <th>Current location</th>
          <th>Agent Name</th>
          <th>Agent Contact Number</th>
          <th>Updated at</th>
        </tr>
      </thead>
      <tbody>
        <%@order.order_transits.each do |transit|%>
          <tr>
            <td>
              <%=transit.location%>
            </td>
            <td>
              <%=transit.agent_name%>
            </td>
            <td>
              <%=transit.agent_phone_number%>
            </td>
            <td>
              <%=transit.updated_at.strftime("%a , %I:%M - %F")%>
            </td>
          </tr>
          <% end %>
      </tbody>
      <%else%>
        <p id="no-content-label">
          No Transaction data updated
        </p>
        <%end%>
  </table>

app/views/users/new.html.erb
<h1>Signup</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
      <%= form_for @user, url: signup_path do |form| %>
      		<div class="form-group">
            <%= form.label :name%>
      			<%= form.text_field :name,:class=>'form-control input-md' %>
      			<%= error_message form, :name%>
      		</div>
          <div class="form-group">
          		<%= form.label :email %>
          		<%= form.text_field :email,:class=>'form-control input-md' %>
          		<%= error_message form,:email%>
          </div>
          <div class="form-group">
        			<%= form.label :password %>
        			<%= form.password_field :password,class: 'form-control' %>
        			<%= error_message form,:password%>
        		</div>
        	<div class="form-group">
        			<%= form.label :password_confirmation %>
        			<%= form.password_field :password_confirmation,class: 'form-control'  %>
        			<%= error_message form,:password_confirmation%>
         </div>
  		   <%= form.submit "Create",:class=>'btn btn-primary'%>
	   <%end%>
  </div>
</div>